Repository jest-community/eslint-plugin-jest-extended, pull requests merged in 2022-08, with the labels that each got.

#16 docs: link to `jest-extended`
  README.md
Labels: documentation

#19 feat: create `prefer-to-have-been-called-once` rule
  README.md
  docs/rules/prefer-to-have-been-called-once.md
  src/__tests__/__snapshots__/rules.test.ts.snap
  src/__tests__/rules.test.ts
  src/rules/__tests__/prefer-to-have-been-called-once.ts
  src/rules/prefer-to-have-been-called-once.ts
Labels: enhancement, rule: prefer-to-have-been-called-once

#20 feat: switch to new scope-based jest fn call parser to support `@jest/globals`
  .github/workflows/nodejs.yml
  package.json
  src/rules/__tests__/prefer-to-be-array.test.ts
  src/rules/__tests__/prefer-to-be-object.test.ts
  src/rules/prefer-to-be-array.ts
  src/rules/prefer-to-be-false.ts
  src/rules/prefer-to-be-object.ts
  src/rules/prefer-to-be-true.ts
  src/rules/prefer-to-have-been-called-once.ts
  src/rules/utils.ts
  src/rules/utils/__tests__/parseJestFnCall.test.ts
  src/rules/utils/accessors.ts
  src/rules/utils/followTypeAssertionChain.ts
  src/rules/utils/index.ts
  src/rules/utils/misc.ts
  src/rules/utils/parseJestFnCall.ts
  yarn.lock
Labels: enhancement, rule: prefer-to-have-been-called-once, rule: utils, rule: prefer-to-be-array, rule: prefer-to-be-object, rule: prefer-to-be-false, rule: prefer-to-be-true

#25 feat: drop support for Node versions 12 and 17
  .github/workflows/nodejs.yml
  package.json
Labels: enhancement

#26 feat: drop support for `eslint@6`
  .github/workflows/nodejs.yml
  package.json
  yarn.lock
Labels: enhancement
